# Vagrant file for running teletraan demo locally.

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, guest: 8888, host: 8888
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  config.vm.synced_folder "../", "/home/vagrant/teletraan"

  config.vm.provider "virtualbox" do |v|
    v.name = "Teletraan Demo Vagrant"
    v.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.provision "shell" do |s|
    s.path = "./demo_provision.sh"
  end
end
