repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/psf/black'
    rev: 23.12.0
    hooks:
      - id: black
        files: "^(deploy-agent|deploy-board)/.*\\.py$"
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: "^(deploy-agent|deploy-board)/.*\\.py$"
  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
        files: "^deploy-board/.*\\.html$"
      - id: djlint-django
        files: "^deploy-board/.*\\.html$"
        args: [--ignore="H031"]
