#!/bin/bash

# POST_DOWNLOAD is executed after the newer version of artifact being downloaded.
# POST_DOWNLOAD script is from the current running version, not from the
# newer version just downloaded.

echo "This is POST_DOWNLOAD!"
