#!/bin/bash

echo Running POST_RESTART script.

# Environment Variable defined in DeployBoard Script Config
echo $PORT

# Built in Environment Variables
echo $ENV_NAME
echo $STAGE_NAME
echo $COMPUTE_ENV_TYPE
echo $DEPLOY_ID
echo $DEPLOY_STEP
echo $OPCODE
echo $DEPLOY_TYPE
echo $BUILD_COMMIT
echo $BUILD_NAME
echo $BUILD_REPO
echo $BUILD_BRANCH
echo $BUILD_ID
echo $BUILD_URL
