#!/bin/bash

# POST_RESTART is the last executed script. Typically perform health check, smoke test, register
# with LB, warm up cache etc.

echo "This is POST_RESTART!"

echo 'TEST='$BUILD_COMMIT
echo 'DEPLOY_ID='$DEPLOY_ID
echo 'TARGET='$TARGET
echo 'ENV_NAME='$ENV_NAME
echo 'STAGE_NAME='$STAGE_NAME
echo 'BUILD_COMMIT='$BUILD_COMMIT
echo 'OPCODE='$OPCODE

