#!/bin/bash

echo Running PRE_DOWNLOAD script.
# Remove old tmp files
rm -r /tmp/deploy-sentinel

# Delete running processes on port 8000
PORT_NUMBER=8000
lsof -i tcp:${PORT_NUMBER} | awk 'NR!=1 {print $2}' | xargs kill
