#!/bin/bash

# PRE_DOWNLOAD is executed before downloading deploy artifact.
# PRE_DOWNLOAD script is from the current running version, not from the
# newer version which is yet to be download.

echo "This is PRE_DOWNLOAD!"
