#!/bin/bash

# RESTARTING is the script to start or restart service.

echo "This is RESTARTING!"

set -e
set -x
#simulate failure
#echo "yes"
#sleep 300
#exit 100

configure-serviceset -c teletraan/config/serviceset.conf
