FROM maven:3.8-openjdk-8-slim AS builder

COPY . /deploy-service

RUN cd /deploy-service && mvn clean package -DskipTests

FROM openjdk:8

ENV PROJECT_DIR=/opt/deploy-service

RUN mkdir $PROJECT_DIR
WORKDIR $PROJECT_DIR

COPY --from=builder /deploy-service/teletraanservice/target/teletraan-service-0.1-SNAPSHOT-bin.tar.gz $PROJECT_DIR
RUN tar zxf teletraan-service-0.1-SNAPSHOT-bin.tar.gz
COPY ./teletraanservice $PROJECT_DIR/teletraanservice

# Default command to run service, do not override it unless for staging run.
# Use "docker logs ID" to view stdout and stderr
CMD ["scripts/run_in_container.sh"]
