FROM maven:3.8-openjdk-8-slim AS builder

COPY . /deploy-service

RUN --mount=type=cache,target=/m2 \
    cd /deploy-service && mvn package -DskipTests -Dmaven.repo.local=/m2 -Dassembly.skipAssembly=true

FROM openjdk:8

ENV PROJECT_DIR=/opt/deploy-service

RUN mkdir $PROJECT_DIR
WORKDIR $PROJECT_DIR

COPY --from=builder /deploy-service/teletraanservice/target $PROJECT_DIR/teletraanservice
COPY teletraanservice/bin $PROJECT_DIR/teletraanservice/bin

CMD ["teletraanservice/bin/run.sh", "-c", "teletraanservice/bin/server.yaml"]