name: Deploy Agent CI

on:
  push:
    paths:
      'deploy-agent/**'
    branches:
      - master
  pull_request:
    paths:
      'deploy-agent/**'
    branches:
      - master


defaults:
  run:
    shell: bash
    working-directory: ./deploy-agent

jobs:
  build:
    strategy:
      matrix:
        include:
          - os-version: "ubuntu-20.04"
            python-version: "3.6"
          - os-version: "ubuntu-20.04"
            python-version: "3.8"
          - os-version: "ubuntu-24.04"
            python-version: "3.12"
    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Tests
        run: |
          tox -v
